### ISSUE TITLE
add image on the qr-code

### ISSUE THREAD

**Issue by dreamofmaks** [werthdavid/ngx-kjua#28]
guys, can someone show me how to add an image on the qr code using base64? i am a little bit confused, i appreciate your attention.

**Comment by werthdavid** [comment]
Hey, it would look like this:
```html

<ngx-kjua
    [text]="'hello'"
   [image]="imageAsBase64"
   [mode]="'image'"
  ></ngx-kjua>
```
where `imageAsBase64` contains the base64 string

**Comment by dreamofmaks** [comment]
Oh, thank you,very much  i've tried this before, but it wasn't working). Have a nice day and weekend.

**Comment by dreamofmaks** [comment]
Oh, and can i add image, if my [render] = " 'canvas' "?

**Comment by werthdavid** [comment]
Yes that should work. What is your problem? is there an error message?

**Comment by dreamofmaks** [comment]
No error messages, but image is not on the qr code((

**Comment by werthdavid** [comment]
Can you provide more information? Like the text content, image content and how you configure ngx-kjua?

**Comment by dreamofmaks** [comment]
<ngx-kjua
      [render] = "'canvas'"
      *ngIf="sms" 
      [text]="sms" 
      [image]="imageAsBase64"
      [mode]="'image'"
      [imageAsCode]="false"
      #QrCode
    >
    </ngx-kjua>

here's a configuration.
And when render = svg - everything is OK, but when render = canvas - something go wrong with that image
![image](https://user-images.githubusercontent.com/64159353/115507955-714aa700-a285-11eb-9cfe-982d6c5c349c.png)

**Comment by werthdavid** [comment]
I'm sorry, I cannot reproduce that... It works fine in my examples. Is it possible to provide the actual base64 string?

**Comment by rbalet** [comment]
@werthdavid I did also get an error while trying to load an image and was able to find a step to reproduce.

Using base64 here are two different stackblitz _(taken from you example, I just did remove the useless information)_

1. Working one  -> https://stackblitz.com/edit/ngx-kjua-example-7-kzxqg3
![image](https://user-images.githubusercontent.com/44493964/132838790-fb91281a-654e-413d-8428-f1cb07ae22b0.png)

2. Not working one -> https://stackblitz.com/edit/ngx-kjua-example-7-q7plql
![image](https://user-images.githubusercontent.com/44493964/132838841-cc81915b-8968-4410-8fcc-f5647d7f352b.png)

### Additional information
I did realize that when I did try to fix the not working example one, I could.

1. re ad the ` implements AfterViewInit {` 
2. Add some space under the `text` variable declaration

![image](https://user-images.githubusercontent.com/44493964/132839075-c553784c-18ef-4f72-91db-f4978f5b7e12.png)

then it would have shown the logo 

![image](https://user-images.githubusercontent.com/44493964/132839104-4725b9f6-3881-4597-a2d0-96fee47109c5.png)


### My analyze
You did add a `setTimeout()` into the `ngAfterViewInit()` which forced your component to be reloaded. which then shown the image. 

I didn't analyze your code since you'll do that better than me, but it seems like you have a problem of change detection with the image, maybe you could use an `async` pipe or something like that. 

If you need more information I'll be glad to help.

Nice library by the way :)

**Comment by werthdavid** [comment]
Oh okay thanks for the information, I'll look into it!

**Comment by werthdavid** [comment]
it looks like the image takes some time to render when the base64-string is "long" and the QR code is ready faster. Let's see..

**Comment by werthdavid** [comment]
please try 1.12.4

**Comment by rbalet** [comment]
@werthdavid Seems to be working for me on the 1.30.0
